language: node_js
node_js:
- '6'
script:
- ./prepare.sh
deploy:
  provider: releases
  api_key:
    secure: WLscrSf1ad9rEmZodg+tnqVo1IBwI5zAuaulC/bojiYmAR9pysFryas6SyGjgFCK9DKbFiaPUZXOWAT9q9uSgsPkWEARqE69BpXiDo4PLX0BVRhXd5C5Z0Neu6f03Zgx9lxY9/CalR3WF+qqrRSouUa2KveyMA1ofv6I+Q410do4qIbVWR5bY9RTU7SukdOQz1Nq4JhOHBNYEGSZEeu2/7kM8g3GJesSstOQaTSvOWSAQKeyj/aD63LfTNAd1zW577vyEjtXgz0xIvafot3WX88jarEJlLwNWciifssco6z1OCOOZ67unygmBiM62h35ism8qt2OX1S239my1L7kaoCNSPwbQ0GvP9foL9UkXl5zfIxUO6ZnkddouC+p5pI7DBSfJ9dJP3lToNJNei8jBa1xeLWByP6G82A5hKKrWBJEj4T2nXQUD5OAhy0cie0qeYHCA4bed4YMtpk3gHPXBkfhCfiq0qj9BOkPl+B0f0g1b6BGBvxfauphURH2QTqwckativGR4jIGipCHJdGA8WihRtHhoQgwppvlFiPsCJF/WaK2eTXpHAiIEZHNo28y3/frl1CBnpM5pFOfXJd2zk0BKQDyMR/0lcOXPrpaZyUt7lpkoVmCsJjIo+/Uf/fCt7vujol5b2YE4/MaedzJXhnXv3FdtyTot4A9FVOLUT4=
  file:
    - windows.zip
    - linux.zip
    - mac.zip
  on:
    repo: openstyles/native-client
